# Generated by Django 5.2.6 on 2025-10-03 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the constituency', max_length=255)),
                ('level', models.CharField(choices=[('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=20)),
                ('legislative_body', models.CharField(help_text="e.g., 'Bundestag', 'Bayerischer Landtag', 'Gemeinderat München'", max_length=255)),
                ('legislative_period_start', models.DateField(help_text='When current period began')),
                ('legislative_period_end', models.DateField(blank=True, help_text='When current period ends (null for ongoing)', null=True)),
                ('region', models.CharField(help_text='Geographic identifier (state code, municipality code, etc.)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional API-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_constituency', models.ForeignKey(blank=True, help_text='For hierarchical relationships (e.g., local within state)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_constituencies', to='letters.constituency')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stub_provider', help_text='Identity verification provider', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Additional verification provider data')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, help_text='Constituency determined from address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_residents', to='letters.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FLAGGED', 'Flagged for Review'), ('REMOVED', 'Removed')], default='PUBLISHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('OFFENSIVE', 'Offensive Content'), ('MISINFORMATION', 'Misinformation'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Details of the report')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ACTION_TAKEN', 'Action Taken')], default='PENDING', max_length=20)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='letters.letter')),
                ('reporter', models.ForeignKey(blank=True, help_text='User who made the report (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('party', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, help_text="e.g., 'Member of Parliament', 'Minister', etc.", max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('term_start', models.DateField(help_text="When this representative's term started")),
                ('term_end', models.DateField(blank=True, help_text="When this representative's term ends", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional API-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='letters.constituency')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='letters.representative'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='letters.letter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='letters', to='letters.tag'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['level', 'region'], name='letters_con_level_9e0e29_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['status', 'user'], name='letters_ide_status_cffd46_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='letters_rep_status_735d23_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['letter', '-created_at'], name='letters_rep_letter__fe909b_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['is_active', 'constituency'], name='letters_rep_is_acti_b9f94a_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['last_name', 'first_name'], name='letters_rep_last_na_36c011_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['letter', '-signed_at'], name='letters_sig_letter__2ef549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('user', 'letter')},
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['-published_at'], name='letters_let_publish_c36136_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['status', '-published_at'], name='letters_let_status_79a7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='letter',
            index=models.Index(fields=['representative', '-published_at'], name='letters_let_represe_bb1b51_idx'),
        ),
    ]
