# Generated by Django 5.2.6 on 2025-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['external_id'], name='letters_com_externa_9f78ab_idx'),
        ),
    ]
