# Generated by Django 5.2.6 on 2025-10-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='level',
            field=models.CharField(choices=[('EU', 'European Union'), ('FEDERAL', 'Federal'), ('STATE', 'State'), ('LOCAL', 'Local')], max_length=20),
        ),
    ]
