# Generated by Django 5.2.6 on 2025-10-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_committee_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords extracted from name and description'),
        ),
    ]
