# Generated by Django 5.2.6 on 2025-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_committee_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='representative',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
