# Generated by Django 5.2.6 on 2025-10-04 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_topicarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Committee name (e.g., 'Ausschuss für Umwelt und Verbraucherschutz')", max_length=255)),
                ('parliament', models.CharField(help_text="Parliament this committee belongs to (e.g., 'Bundestag', 'EU-Parlament', 'Bayern')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the committee's responsibilities")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional API data (api_id, abgeordnetenwatch_url, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_area', models.ForeignKey(blank=True, help_text='Related TopicArea in our taxonomy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees', to='letters.topicarea')),
            ],
            options={
                'ordering': ['parliament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('alternate_member', 'Alternate Member'), ('chair', 'Chair/Vorsitz'), ('deputy_chair', 'Deputy Chair/Stellv. Vorsitz')], help_text='Role in the committee', max_length=50)),
                ('additional_roles', models.JSONField(blank=True, default=list, help_text='Additional roles (from API committee_roles_additional field)')),
                ('start_date', models.DateField(blank=True, help_text='When membership started', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When membership ended (null for active)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional API data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='letters.committee')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='letters.representative')),
            ],
            options={
                'ordering': ['representative', 'committee'],
            },
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['parliament'], name='letters_com_parliam_8442d9_idx'),
        ),
        migrations.AddIndex(
            model_name='committee',
            index=models.Index(fields=['topic_area'], name='letters_com_topic_a_7a8efd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committee',
            unique_together={('name', 'parliament')},
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['representative'], name='letters_com_represe_0a772a_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['committee'], name='letters_com_committ_d7d9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='committeemembership',
            index=models.Index(fields=['role'], name='letters_com_role_22257b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeemembership',
            unique_together={('representative', 'committee')},
        ),
    ]
