# Generated by Django 5.2.6 on 2025-10-06 09:14

from django.db import migrations, models


def forward_copy_topic_areas(apps, schema_editor):
    Committee = apps.get_model('letters', 'Committee')

    for committee in Committee.objects.exclude(topic_area__isnull=True):
        topic = committee.topic_area
        if topic:
            committee.topic_areas.set([topic])


def backward_restore_topic_area(apps, schema_editor):
    Committee = apps.get_model('letters', 'Committee')

    for committee in Committee.objects.all():
        topic = committee.topic_areas.order_by('pk').first()
        committee.topic_area_id = topic.pk if topic else None
        committee.save(update_fields=['topic_area'])


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_representative_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='topic_areas',
            field=models.ManyToManyField(blank=True, related_name='committees', to='letters.topicarea'),
        ),
        migrations.AddField(
            model_name='representative',
            name='topic_areas',
            field=models.ManyToManyField(blank=True, related_name='representatives', to='letters.topicarea'),
        ),
        migrations.RunPython(forward_copy_topic_areas, backward_restore_topic_area),
        migrations.RemoveIndex(
            model_name='committee',
            name='letters_com_topic_a_7a8efd_idx',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='topic_area',
        ),
    ]
