# Generated by Django 5.2.6 on 2025-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_committee_committeemembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('alternate_member', 'Alternate Member'), ('chair', 'Chair/Vorsitz'), ('deputy_chair', 'Deputy Chair/Stellv. Vorsitz'), ('foreperson', 'Foreperson/Obfrau/Obmann')], help_text='Role in the committee', max_length=50),
        ),
    ]
