# Generated by Django 5.2.6 on 2025-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_alter_committeemembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='focus_areas',
            field=models.TextField(blank=True, help_text="Comma-separated list of policy focus areas (e.g., 'climate policy, energy transition, transport'). Can be populated from Wikipedia, speeches, or self-reported data."),
        ),
    ]
