# Generated by Django 5.2.6 on 2025-10-06 09:58

import django.db.models.deletion
from django.db import migrations, models


def populate_constituencies(apps, schema_editor):
    IdentityVerification = apps.get_model('letters', 'IdentityVerification')

    qs = IdentityVerification.objects.exclude(constituency__isnull=True)
    for verification in qs.iterator():
        constituency = verification.constituency
        if not constituency:
            continue
        updates = {}
        scope = getattr(constituency, 'scope', '') or ''
        if scope.startswith('FEDERAL'):
            updates['federal_constituency_id'] = constituency.id
        if scope.startswith('STATE'):
            updates['state_constituency_id'] = constituency.id
        if updates:
            IdentityVerification.objects.filter(pk=verification.pk).update(**updates)


def rollback_constituencies(apps, schema_editor):
    IdentityVerification = apps.get_model('letters', 'IdentityVerification')

    for verification in IdentityVerification.objects.iterator():
        fallback_id = (
            verification.constituency_id
            or verification.federal_constituency_id
            or verification.state_constituency_id
        )
        if fallback_id and verification.constituency_id != fallback_id:
            IdentityVerification.objects.filter(pk=verification.pk).update(constituency_id=fallback_id)


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_remove_committee_letters_com_topic_a_7a8efd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='federal_constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_verified_residents', to='letters.constituency'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='state_constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_verified_residents', to='letters.constituency'),
        ),
        migrations.RunPython(populate_constituencies, rollback_constituencies),
    ]
