# Generated by Django 5.2.6 on 2025-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_identityverification_federal_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='verification_type',
            field=models.CharField(choices=[('THIRD_PARTY', 'Third-party Provider'), ('SELF_DECLARED', 'Self-declared')], default='THIRD_PARTY', max_length=20),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified (third party)'), ('SELF_DECLARED', 'Self-declared'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
