# Generated by Django 5.2.6 on 2025-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_identityverification_verification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicarea',
            name='legal_basis_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicarea',
            name='legal_basis',
            field=models.CharField(max_length=255),
        ),
    ]
