# Generated by Django 5.2.6 on 2025-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_topicarea_legal_basis_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AddField(
            model_name='committeemembership',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AddField(
            model_name='parliament',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AddField(
            model_name='parliamentterm',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this was synced from external API', null=True),
        ),
        migrations.AlterField(
            model_name='topicarea',
            name='competency_type',
            field=models.CharField(choices=[('EXCLUSIVE', 'Ausschließliche Gesetzgebung'), ('CONCURRENT', 'Konkurrierende Gesetzgebung'), ('DEVIATION', 'Abweichungsgesetzgebung'), ('JOINT', 'Gemeinschaftsaufgaben'), ('RESIDUAL', 'Länderkompetenz'), ('SHARED', 'Geteilte Zuständigkeit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='topicarea',
            name='primary_level',
            field=models.CharField(choices=[('EU', 'European Union'), ('FEDERAL', 'Federal (Bund)'), ('STATE', 'State (Land)'), ('LOCAL', 'Local (Kommune)')], max_length=20),
        ),
    ]
