# Generated by Django 5.2.6 on 2025-10-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_add_last_synced_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='districts',
        ),
        migrations.DeleteModel(
            name='ElectoralDistrict',
        ),
    ]
