# Generated by Django 5.2.6 on 2025-10-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_alter_letter_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_hash', models.CharField(db_index=True, help_text='SHA256 hash of normalized address for fast lookup', max_length=64, unique=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True, help_text='False if geocoding failed, to avoid repeated failed lookups')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geocode Cache Entry',
                'verbose_name_plural': 'Geocode Cache Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
