# Generated by Django 5.2.6 on 2025-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0012_geocodecache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='city',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='country',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='state',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='street_address',
        ),
    ]
