# Generated by Django 5.2.6 on 2025-10-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0013_remove_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='wahlkreis_id',
            field=models.CharField(blank=True, help_text='Geographic Wahlkreis identifier (e.g., WKR_NR from GeoJSON)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='constituencies',
            field=models.ManyToManyField(blank=True, related_name='verified_residents_all', to='letters.constituency'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='eu_wahlkreis',
            field=models.CharField(default='DE', help_text='EU Wahlkreis (always DE for Germany)', max_length=10),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='federal_wahlkreis_number',
            field=models.CharField(blank=True, help_text='Federal Wahlkreis number (1-299)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='state_wahlkreis_number',
            field=models.CharField(blank=True, help_text='State-specific Wahlkreis identifier', max_length=10, null=True),
        ),
    ]
