# Generated by Django 5.2.6 on 2025-10-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0015_migrate_constituency_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='federal_constituency',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='state_constituency',
        ),
    ]
