# Generated by Django 5.2.6 on 2025-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0017_populate_missing_wahlkreis_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='wahlkreis_id',
            field=models.CharField(
                help_text='Geographic Wahlkreis identifier (e.g., WKR_NR from GeoJSON)',
                max_length=20,
                unique=True
            ),
        ),
    ]
