# Generated by Django 5.2.6 on 2025-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0018_make_wahlkreis_id_required'),
    ]

    operations = [
        # Rename field
        migrations.RenameField(
            model_name='constituency',
            old_name='wahlkreis_id',
            new_name='list_id',
        ),
        # Remove unique constraint from list_id field itself
        migrations.AlterField(
            model_name='constituency',
            name='list_id',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                help_text="Identifier for WahlkreisResolver lookups (e.g., '001', 'BY-0001', 'BUND-BY-LIST')"
            ),
        ),
        # Add unique_together constraint (list_id is only unique per parliament_term)
        migrations.AlterUniqueTogether(
            name='constituency',
            unique_together={('list_id', 'parliament_term')},
        ),
    ]
