"""
Management command to populate the TopicArea taxonomy with German governmental competencies.
Translated classification based on the Grundgesetz (GG) division of powers.
"""

from django.core.management.base import BaseCommand
from django.utils.text import slugify

from letters.models import TopicArea


class Command(BaseCommand):
    help = 'Lädt die Themen-Taxonomie gemäß Grundgesetz (Bund, Länder, Kommunen, EU)'

    def handle(self, *args, **options):
        self.stdout.write('Lade Themen-Taxonomie …')

        TopicArea.objects.all().delete()

        topics_data = [
            # BUNDESKOMPETENZEN AUSSCHLIESSLICH (Art. 71, 73 GG)
            {
                'name': 'Außenpolitik',
                'description': 'Internationale Beziehungen, Verträge, diplomatische Vertretungen',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'außenpolitik, diplomatie, internationale beziehungen, außenministerium, verträge, botschaften, konsulate, völkerrecht, un, vereinte nationen',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 1 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Verteidigung',
                'description': 'Bundeswehr, Sicherheitspolitik, Zivilschutz',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'verteidigung, bundeswehr, militär, sicherheitspolitik, nato, zivilschutz, wehrpflicht, streitkräfte, landesverteidigung',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 1 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Staatsangehörigkeit',
                'description': 'Staatsbürgerschaft, Ein- und Ausbürgerung, Passwesen',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'staatsangehörigkeit, staatsbürgerschaft, einbürgerung, ausbürgerung, pass, passwesen, reisepass, personalausweis, deutscher, deutsche staatsangehörigkeit',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Freizügigkeit und Meldewesen',
                'description': 'Freizügigkeit, Melde- und Ausweiswesen, Ein- und Auswanderung',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'freizügigkeit, meldewesen, melderegister, ausweiswesen, einwanderung, auswanderung, auslieferung, wohnsitz, umzug',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 3 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Währung und Geldwesen',
                'description': 'Euro, Bundesbank, Geldpolitik, Münzwesen, Maße und Gewichte',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'währung, euro, geldpolitik, bundesbank, zentralbank, inflation, zinsen, münzwesen, geldsystem, maße, gewichte, zeit, zeitbestimmung',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 4 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Zoll- und Außenhandel',
                'description': 'Zollwesen, Außenwirtschaft, Handelsabkommen, Warenverkehr',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'zoll, außenhandel, handelsabkommen, import, export, zolltarif, außenwirtschaft, warenverkehr, grenzschutz, freihandel, handelspolitik',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 5 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Kulturgüterschutz',
                'description': 'Schutz deutschen Kulturgutes gegen Abwanderung ins Ausland',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'kulturgüterschutz, kulturgut, kunstschutz, kulturgut ausfuhr, kulturerbe, kunstexport, denkmalschutz international',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 5a GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Luftverkehr',
                'description': 'Luftverkehrsverwaltung, Flugsicherung, Flughäfen',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'luftverkehr, flugsicherung, luftfahrt, flughafen, luftfahrtbehörde, flugverkehr, zivilluftfahrt, flugsicherheit',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 6 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Eisenbahnen des Bundes',
                'description': 'Bundeseigene Eisenbahnen, Schienenwege, Deutsche Bahn',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'bundeseisenbahn, deutsche bahn, db, schienenwege, eisenbahnverkehr, bahninfrastruktur, schienennetz',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 6a GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Post und Telekommunikation',
                'description': 'Postwesen, Telekommunikation, digitale Infrastruktur',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'post, telekommunikation, deutsche post, briefverkehr, paket, telefon, internet, digitale infrastruktur, breitband, mobilfunk',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 7 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Bundesbeamtenrecht',
                'description': 'Rechtsverhältnisse der Bundesbediensteten',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'bundesbeamte, beamtenrecht, öffentlicher dienst bund, besoldung bund, versorgung bundesbeamte, beamtenverhältnis',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 8 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Gewerblicher Rechtsschutz',
                'description': 'Urheberrecht, Patentrecht, Markenschutz',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'urheberrecht, patentrecht, markenschutz, geistiges eigentum, patent, marke, gewerblicher rechtsschutz, verlagsrecht, copyright',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 9 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Bundespolizei und Verfassungsschutz',
                'description': 'BKA, Verfassungsschutz, internationale Verbrechensbekämpfung',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'bundeskriminalamt, bka, verfassungsschutz, bundespolizei, terrorismusabwehr, terrorismus, verfassungsschutz, internationale kriminalität, sicherheitsbehörde',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 9a, 10 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Bundesstatistik',
                'description': 'Statistik für Bundeszwecke',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'statistik, bundesstatistik, destatis, statistisches bundesamt, volkszählung, zensus, datenerhebung',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 11 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Waffen- und Sprengstoffrecht',
                'description': 'Waffengesetz, Sprengstoffrecht, Waffenbesitz',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'waffenrecht, waffengesetz, sprengstoffrecht, waffenbesitz, waffenschein, munition, sprengstoff, schusswaffen',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 12 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Kriegsopferversorgung',
                'description': 'Versorgung der Kriegsbeschädigten und Kriegshinterbliebenen',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'kriegsopferversorgung, kriegsbeschädigte, kriegshinterbliebene, kriegsgräber, kriegsgefangene, versorgung kriegsopfer',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 13 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },
            {
                'name': 'Kernenergie',
                'description': 'Atomenergie, kerntechnische Anlagen, Strahlenschutz, Endlagerung',
                'primary_level': 'FEDERAL',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'kernenergie, atomenergie, atomkraft, kernkraftwerk, akw, strahlenschutz, radioaktivität, endlagerung, atommüll, nuklear',
                'legal_basis': 'Art. 73 Abs. 1 Nr. 14 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_73.html',
            },

            # KONKURRIERENDE GESETZGEBUNG (Art. 72, 74 GG)
            {
                'name': 'Bürgerliches und Strafrecht',
                'description': 'Zivilrecht, Strafrecht, Gerichtsverfahren, Justiz',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'bürgerliches recht, zivilrecht, strafrecht, justiz, gericht, staatsanwaltschaft, gerichtsbarkeit, bgb, stgb, prozessrecht, zivilprozess, strafprozess',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 1 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Personenstandswesen',
                'description': 'Standesämter, Geburts-, Ehe- und Sterberegister',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'personenstand, standesamt, geburtsregister, heiratsregister, sterbeurkunde, eheschließung, geburtsurkunde, personenstandsregister',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Vereins- und Versammlungsrecht',
                'description': 'Vereinsrecht, Versammlungsfreiheit, Demonstrationen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'vereinsrecht, versammlungsrecht, versammlungsfreiheit, demonstration, kundgebung, vereinsregister, versammlungsgesetz',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 3 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Aufenthalt und Asyl',
                'description': 'Aufenthaltsrecht, Flüchtlingspolitik, Migration',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'aufenthalt, asyl, migration, flüchtlinge, visum, ausländerrecht, aufenthaltstitel, niederlassung, asylbewerber',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 4, 6 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Sozialversicherung',
                'description': 'Renten-, Kranken-, Pflege- und Arbeitslosenversicherung',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'sozialversicherung, rentenversicherung, krankenversicherung, pflegeversicherung, arbeitslosengeld, bürgergeld, sozialleistungen',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 7, 12 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Wirtschaftspolitik',
                'description': 'Industrie, Energie, Handel, Finanzmärkte',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'wirtschaftspolitik, industriepolitik, energiepolitik, handel, finanzmarkt, bergbau, gewerbe, industrie',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 11 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Arbeitsrecht',
                'description': 'Arbeitsverhältnisse, Arbeitsschutz, Vermittlung',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'arbeitsrecht, arbeitsschutz, beschäftigung, arbeitsvermittlung, jobcenter, arbeitnehmerrechte, betriebsverfassung',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 12 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Forschungsförderung',
                'description': 'Wissenschafts- und Bildungsförderung, BAföG',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'forschungsförderung, wissenschaft, innovation, bafög, studienförderung, hochschulförderung, ausbildungsförderung',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 13 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Enteignungsrecht',
                'description': 'Enteignung für öffentliche Zwecke',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'enteignung, enteignungsrecht, öffentliche zwecke, entschädigung, grundstücksenteignung',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 14 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Wirtschaftsmacht und Wettbewerb',
                'description': 'Kartellrecht, Wettbewerbsrecht, Monopolkontrolle',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'kartellrecht, wettbewerbsrecht, monopol, bundeskartellamt, wettbewerb, marktmacht, wirtschaftsmacht',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 16 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Landwirtschaft und Ernährung',
                'description': 'Agrarförderung, Ernährungssicherung, Fischerei',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'landwirtschaft, agrarförderung, ernährung, fischerei, küstenfischerei, küstenschutz, forstwirtschaft, agrarpolitik',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 17 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Wohnungswesen',
                'description': 'Wohnraumförderung, Mietrecht, Bodenrecht',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'wohnen, mietrecht, wohnungsbau, mietpreisbremse, bodenrecht, sozialer wohnungsbau, grundstücksverkehr',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 18 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Gesundheitswesen',
                'description': 'Seuchenbekämpfung, Heilberufe, Arzneimittel',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'gesundheit, gesundheitspolitik, seuchenbekämpfung, heilberuf, apotheke, arzneimittel, medizin, arzt, krankenhaus',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 19, 19a GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Verbraucherschutz und Ernährung',
                'description': 'Lebensmittelrecht, Verbraucherschutz, Tierschutz',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'verbraucherschutz, lebensmittel, lebensmittelsicherheit, verbraucherrecht, tierschutz, futtermittel',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 20 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Schifffahrt',
                'description': 'Seeschifffahrt, Binnenschifffahrt, Wasserstraßen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'schifffahrt, seeschifffahrt, binnenschifffahrt, wasserstraße, schifffahrtsrecht, hafen, seerecht',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 21 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Straßenverkehr',
                'description': 'Straßenverkehrsrecht und Kraftfahrwesen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'straßenverkehr, straßenverkehrsordnung, verkehrssicherheit, führerschein, kfz-zulassung, stvo, kraftfahrzeug',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 22 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Bundesfernstraßen',
                'description': 'Autobahnen, Bundesstraßen, überregionale Infrastruktur',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'bundesstraße, autobahn, fernstraße, bundesverkehr, verkehrsinfrastruktur, fernverkehr',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 22 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Schienenbahnen',
                'description': 'Nicht-bundeseigene Eisenbahnen, Regionalbahnen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'schienenbahn, regionalbahn, s-bahn, straßenbahn, eisenbahn regional',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 23 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Umweltschutz',
                'description': 'Abfallwirtschaft, Luftreinhaltung, Lärmbekämpfung',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'umweltschutz, klimawandel, luftreinhaltung, emission, abfallwirtschaft, lärmschutz, immissionsschutz, klima',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 24 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Staatshaftung',
                'description': 'Haftung des Staates für Amtspflichtverletzungen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'staatshaftung, amtshaftung, behördenhaftung, schadensersatz staat, öffentliche haftung',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 25 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Künstliche Befruchtung',
                'description': 'Reproduktionsmedizin, Gentechnik am Menschen',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'künstliche befruchtung, reproduktionsmedizin, ivf, gentechnik, embryonenschutz, stammzellen',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 26 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },
            {
                'name': 'Öffentlicher Dienst der Länder',
                'description': 'Besoldung und Versorgung der Landesbediensteten',
                'primary_level': 'FEDERAL',
                'competency_type': 'CONCURRENT',
                'keywords': 'öffentlicher dienst länder, landesbeamte, besoldung länder, versorgung beamte, beamtenrecht länder',
                'legal_basis': 'Art. 74 Abs. 1 Nr. 27 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_74.html',
            },

            # ABWEICHUNGSGESETZGEBUNG (Art. 72 Abs. 3 GG)
            {
                'name': 'Jagdwesen',
                'description': 'Jagdrecht, Wildtiermanagement, Jagdscheine',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'jagd, jagdrecht, jagdschein, wildtiere, jäger, wildhege, jagdgesetz',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 28 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },
            {
                'name': 'Naturschutz',
                'description': 'Naturschutz, Landschaftspflege, Artenschutz',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'naturschutz, landschaftspflege, artenschutz, biodiversität, naturschutzgebiet, nationalpark, umweltschutz',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 29 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },
            {
                'name': 'Bodenverteilung',
                'description': 'Grundstücksverkehr, Bodenverwertung',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'bodenverteilung, grundstücksverkehr, bodenpolitik, flächennutzung',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 30 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },
            {
                'name': 'Raumordnung',
                'description': 'Überregionale Raumplanung und Entwicklung',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'raumordnung, raumplanung, regionalplanung, bundesplanung, landesplanung, siedlungsstruktur',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 31 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },
            {
                'name': 'Wasserhaushalt',
                'description': 'Wasserrecht, Gewässer, Hochwasserschutz',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'wasserhaushalt, wasserrecht, wasserwirtschaft, hochwasserschutz, gewässer, wasserschutz',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 32 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },
            {
                'name': 'Hochschulzulassung',
                'description': 'Zugang und Abschlüsse an Hochschulen',
                'primary_level': 'FEDERAL',
                'competency_type': 'DEVIATION',
                'keywords': 'hochschulzulassung, numerus clausus, nc, studienplatz, zulassung, studium, hochschulabschluss',
                'legal_basis': 'Art. 72 Abs. 3, Art. 74 Abs. 1 Nr. 33 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_72.html',
            },

            # GEMEINSCHAFTSAUFGABEN (Art. 91a, 91b GG)
            {
                'name': 'Regionale Wirtschaftsförderung',
                'description': 'Verbesserung der regionalen Wirtschaftsstruktur',
                'primary_level': 'FEDERAL',
                'competency_type': 'JOINT',
                'keywords': 'regionalförderung, strukturförderung, wirtschaftsförderung regional, gemeinschaftsaufgabe, strukturpolitik',
                'legal_basis': 'Art. 91a Abs. 1 Nr. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_91a.html',
            },
            {
                'name': 'Agrarstruktur und Küstenschutz',
                'description': 'Verbesserung der Agrarstruktur und des Küstenschutzes',
                'primary_level': 'FEDERAL',
                'competency_type': 'JOINT',
                'keywords': 'agrarstruktur, küstenschutz, agrarpolitik, strukturverbesserung landwirtschaft, gemeinschaftsaufgabe',
                'legal_basis': 'Art. 91a Abs. 1 Nr. 3 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_91a.html',
            },
            {
                'name': 'Bildungsplanung (Kooperation)',
                'description': 'Kooperation bei Leistungsfähigkeit des Bildungswesens',
                'primary_level': 'FEDERAL',
                'competency_type': 'JOINT',
                'keywords': 'bildungsplanung, bildungsforschung, bildungsmonitoring, pisa, bildungssystem, kooperation bildung',
                'legal_basis': 'Art. 91b Abs. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_91b.html',
            },
            {
                'name': 'Wissenschafts- und Forschungsförderung',
                'description': 'Förderung von Wissenschaft und Forschung von überregionaler Bedeutung',
                'primary_level': 'FEDERAL',
                'competency_type': 'JOINT',
                'keywords': 'forschungsförderung, wissenschaftsförderung, dfg, forschung überregional, gemeinschaftsaufgabe forschung',
                'legal_basis': 'Art. 91b Abs. 1 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_91b.html',
            },

            # LÄNDERKOMPETENZEN (Residualkompetenz nach Art. 70 GG)
            {
                'name': 'Schulbildung',
                'description': 'Schulsystem, Lehrpläne, Schulaufsicht',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'schule, schulpolitik, schulsystem, lehrplan, grundschule, gymnasium, abitur, realschule, hauptschule, bildung',
                'legal_basis': 'Art. 70 GG (Kulturhoheit der Länder)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Hochschulen und Forschung',
                'description': 'Landeshochschulen, Wissenschaft, Forschung',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'hochschule, universität, hochschulpolitik, landeshochschule, forschung, wissenschaft, fachhochschule',
                'legal_basis': 'Art. 70 GG (Kulturhoheit der Länder)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Kultur und Medien',
                'description': 'Landeskultur, Museen, Rundfunk, Denkmalschutz',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'kulturpolitik, museen, theater, rundfunk, medienaufsicht, denkmalschutz, oper, orchester, kulturförderung',
                'legal_basis': 'Art. 70 GG (Kulturhoheit der Länder)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Rundfunk und Medien',
                'description': 'Öffentlich-rechtlicher Rundfunk, Landesmedienanstalten',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'rundfunk, fernsehen, öffentlich-rechtlich, ard, zdf, landesrundfunk, medienanstalt, rundfunkstaatsvertrag',
                'legal_basis': 'Art. 70 GG (Kulturhoheit der Länder)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Innere Sicherheit',
                'description': 'Landespolizei, Ordnungsrecht, Versammlungen',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'landespolizei, polizeirecht, innere sicherheit, ordnungsamt, versammlungsrecht, polizei, sicherheit',
                'legal_basis': 'Art. 30, 70 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Strafvollzug',
                'description': 'Justizvollzugsanstalten, Strafvollzugsrecht',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'strafvollzug, gefängnis, justizvollzug, jva, haft, strafvollzugsrecht, gefängnisse',
                'legal_basis': 'Länderkompetenz seit Föderalismusreform 2006',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Kommunalaufsicht',
                'description': 'Kommunales Verfassungs- und Finanzrecht, Gemeindestruktur',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'kommunalpolitik, gemeindeordnung, kommunalaufsicht, finanzausgleich, kommunalverwaltung, gemeinde, landkreis',
                'legal_basis': 'Landeskommunalrecht (Art. 28 GG)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Landesinfrastruktur',
                'description': 'Landesstraßen, Regionalverkehr, ÖPNV-Planung',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'landesstraße, regionalverkehr, öpnv, verkehrsverbund, verkehrsplanung land, nahverkehr',
                'legal_basis': 'Art. 30, 70 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Bauordnungsrecht',
                'description': 'Landesbauordnungen, Baugenehmigungen, Bauaufsicht',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'bauordnung, landesbauordnung, baugenehmigung, bauaufsicht, baurecht, bauvorschriften',
                'legal_basis': 'Art. 70 GG (Länderkompetenz)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Presserecht',
                'description': 'Landespressegesetze, Pressefreiheit',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'presserecht, landespressegesetz, pressefreiheit, presse, journalismus, medienrecht',
                'legal_basis': 'Art. 70 GG (Länderkompetenz)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Ladenschluss und Gaststätten',
                'description': 'Öffnungszeiten, Gaststättenrecht',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'ladenschluss, öffnungszeiten, gaststättenrecht, gaststätte, ladenöffnung, verkaufsoffener sonntag',
                'legal_basis': 'Länderkompetenz seit Föderalismusreform 2006',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },
            {
                'name': 'Landesbeamtenrecht',
                'description': 'Besoldung, Versorgung und Laufbahn der Landesbeamten',
                'primary_level': 'STATE',
                'competency_type': 'RESIDUAL',
                'keywords': 'landesbeamte, besoldung land, versorgung beamte, laufbahnrecht, beamtenrecht land, öffentlicher dienst',
                'legal_basis': 'Länderkompetenz seit Föderalismusreform 2006',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_70.html',
            },

            # KOMMUNALE EBENE (Selbstverwaltung nach Art. 28 Abs. 2 GG)
            {
                'name': 'Kommunale Dienstleistungen',
                'description': 'Stadtwerke, Abfallentsorgung, Wasser, Energie',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'kommunale dienstleistungen, stadtwerke, abfallentsorgung, wasser, strom, gas, stadtreinigung, müllabfuhr',
                'legal_basis': 'Art. 28 Abs. 2 GG (Kommunale Selbstverwaltung)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Stadtentwicklung',
                'description': 'Bauleitplanung, städtebauliche Entwicklung, Quartiere',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'stadtentwicklung, bauleitplanung, städtebau, stadtplanung, quartiersentwicklung, bebauungsplan, flächennutzungsplan',
                'legal_basis': 'BauGB / Art. 28 Abs. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Lokale Infrastruktur',
                'description': 'Gemeindestraßen, lokaler ÖPNV, kommunale Infrastruktur',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'gemeindestraße, kommunalstraße, busverkehr, stadtbus, verkehr lokal, straßenbau gemeinde',
                'legal_basis': 'Art. 28 Abs. 2 GG (Kommunale Selbstverwaltung)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Kultur und Sport vor Ort',
                'description': 'Bibliotheken, Sportstätten, Vereine, Freizeit',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'kommunale kultur, kulturförderung, sportförderung, sportvereine, sportstätten, freizeitangebot, bibliothek, schwimmbad',
                'legal_basis': 'Art. 28 Abs. 2 GG (Kommunale Selbstverwaltung)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Öffentliche Ordnung (kommunal)',
                'description': 'Märkte, Lärmschutz, örtliche Sicherheit',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'öffentliche ordnung, marktordnung, lärmschutz, ordnungsamt, straßenreinigung, kommunale sicherheit, markt',
                'legal_basis': 'Art. 28 Abs. 2 GG (Kommunale Selbstverwaltung)',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Kinder- und Jugendhilfe',
                'description': 'Kindergärten, Jugendzentren, Jugendamt',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'kindergarten, kita, jugendhilfe, jugendamt, kinderbetreuung, jugendarbeit, kinder, jugend',
                'legal_basis': 'SGB VIII / Art. 28 Abs. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Soziale Dienste (kommunal)',
                'description': 'Sozialamt, Sozialhilfe, Wohngeld',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'sozialamt, sozialhilfe, wohngeld, grundsicherung, soziale dienste, bürgergeld kommune',
                'legal_basis': 'SGB XII / Art. 28 Abs. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },
            {
                'name': 'Feuerwehr und Katastrophenschutz',
                'description': 'Freiwillige und Berufsfeuerwehr, Rettungsdienst',
                'primary_level': 'LOCAL',
                'competency_type': 'RESIDUAL',
                'keywords': 'feuerwehr, katastrophenschutz, rettungsdienst, notarzt, brandschutz, freiwillige feuerwehr',
                'legal_basis': 'Landesgesetze / Art. 28 Abs. 2 GG',
                'legal_basis_url': 'https://www.gesetze-im-internet.de/gg/art_28.html',
            },

            # EU-KOMPETENZEN
            {
                'name': 'EU-Binnenmarkt',
                'description': 'Europäischer Binnenmarkt, Wettbewerbsrecht, Freizügigkeit',
                'primary_level': 'EU',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'eu binnenmarkt, freizügigkeit, wettbewerbspolitik, beihilfenrecht, warenverkehr, dienstleistungsfreiheit, vier freiheiten',
                'legal_basis': 'AEUV Art. 3, 26',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Gemeinsame Handelspolitik',
                'description': 'EU-Handelsabkommen, Zollunion, Welthandel',
                'primary_level': 'EU',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'eu handelspolitik, handelsabkommen, zollunion, internationaler handel, handelsverhandlungen, wto',
                'legal_basis': 'AEUV Art. 3, 206 ff.',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Währungsunion',
                'description': 'Euro, Europäische Zentralbank, Geldpolitik',
                'primary_level': 'EU',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'euro, ezb, europäische zentralbank, währungsunion, geldpolitik eu, eurozone, währung',
                'legal_basis': 'AEUV Art. 3, 119 ff.',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Wettbewerbsregeln',
                'description': 'Kartellrecht, Fusionskontrolle, staatliche Beihilfen',
                'primary_level': 'EU',
                'competency_type': 'EXCLUSIVE',
                'keywords': 'wettbewerbsrecht eu, kartellrecht eu, fusionskontrolle, beihilfen, eu kommission wettbewerb',
                'legal_basis': 'AEUV Art. 101 ff.',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Gemeinsame Agrarpolitik',
                'description': 'EU-Agrarförderung, GAP, Agrarmärkte',
                'primary_level': 'EU',
                'competency_type': 'SHARED',
                'keywords': 'gap, gemeinsame agrarpolitik, agrarsubventionen, eu agrarförderung, landwirtschaft eu',
                'legal_basis': 'AEUV Art. 4, 38 ff.',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Umwelt- und Klimapolitik',
                'description': 'EU-Klimaziele, Umweltstandards, Green Deal',
                'primary_level': 'EU',
                'competency_type': 'SHARED',
                'keywords': 'eu klimapolitik, green deal, klimaziele, co2 reduktion, umweltpolitik eu, emissionshandel',
                'legal_basis': 'AEUV Art. 4, 191 ff.',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Verbraucherschutz (EU)',
                'description': 'EU-Produktstandards, Verbraucherrechte',
                'primary_level': 'EU',
                'competency_type': 'SHARED',
                'keywords': 'verbraucherschutz eu, produktstandards, ce kennzeichnung, verbraucherrechte eu',
                'legal_basis': 'AEUV Art. 4, 169',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:12012E/TXT',
            },
            {
                'name': 'Datenschutz (EU)',
                'description': 'DSGVO, EU-Datenschutzrecht',
                'primary_level': 'EU',
                'competency_type': 'SHARED',
                'keywords': 'dsgvo, datenschutz eu, datenschutzgrundverordnung, datenschutzrecht, gdpr',
                'legal_basis': 'DSGVO / AEUV Art. 16',
                'legal_basis_url': 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32016R0679',
            },
        ]

        created_count = 0
        for topic_data in topics_data:
            topic_data['slug'] = slugify(topic_data['name'])
            topic = TopicArea.objects.create(**topic_data)
            created_count += 1
            self.stdout.write(
                self.style.SUCCESS(
                    f"  ✓ {topic.name} ({topic.get_competency_type_display()})"
                )
            )

        self.stdout.write(
            self.style.SUCCESS(f"\nErfolgreich {created_count} Themenbereiche geladen")
        )
